#!/bin/bash

clear

NUMARGS=2
E_BADARGS=80

returnString=$2
filename=$1 

#Check to see if all the parameters were passed properly
if [ $# -ne $NUMARGS ]
then
	echo "Usage `basename $0` Filename1 StringToRotate"
	exit $E_BADARGS
fi

#Rotate function, need to pass a word and the amount of times to rotate
rotat () {
	ROTARGS=2
	E_BADROT=85
	if [ $# -ne $ROTARGS ]
	then
		echo "Usage `basename $0`:$FUNCNAME <StringToRot> <num>"
		exit $E_BADROT
	fi
	string=$1
	shift=$2

	length=${#string}
	#By using this global variable you can change the value with multiple function calls
	#Try looking up parameters in bash, don't know if it's possible
	returnString=${string:$length-$shift:$shift}${string:0:$length-$shift}
}

#rotat $returnString 2
#rotat $returnString 2
#echo $returnString
while read line
do
	#make this case take action on different functions
	case $( echo $line | awk '{ print $1 }' ) in
		"rotate")	echo "rotate";;
		"move")		echo "move";;
		"swap")		echo "swap";;
		"reverse")	echo "reverse";;
		*)	echo "Command Not recongnized";;
esac
done<$filename


#echo "Hello $USER"

